### ISSUE TITLE
Deleted secret isn't recreated until refresh

### ISSUE THREAD

**Issue by jeffa5** [external-secrets/external-secrets#344] opened 2021-08-25 11:13 UTC
**Describe the solution you'd like**

When a secret (created from an ExternalSecret) is deleted it isn't recreated until the refresh happens (if one will).
The status field on the ExternalSecret remains in `Ready` state despite one of the conditions being `  # - The target secret exists` (from [this page](https://external-secrets.io/api-externalsecret/)).

Instead, it should be recreated immediately.

**What is the added value?**

Deleted secrets that should exist get recreated.

**Give us examples of the outcome**

Deleted secrets get recreated if they are owned by the operator.

**Observations (Constraints, Context, etc):**

This may only be possible with the `creationPolicy: Owner` due to needing the OwnerReference on the secret.

Using:
- Azure Key Vault
- K8s 1.20.5
- 0.3.3 of the helm chart

**Comment by alekc** [comment] 2021-08-28 14:39
Moved this comment from PR to here since it's probably a better place to discuss. 

---

This is tougher than it looks due to a catch 22.

While I was working on the above, I came to realise that we do not store the latest snapshot inside the externalsecret object. As a consequence, at the moment we do not know what's supposed to be inside the kind=secret. 

Here are some thoughts:

- We can easily deal with deleted secret, as long as `es.Status.SyncedResourceVersion != ""` , kind=secret should exist and we can trigger the global refresh which will recreate it with proper values. 
- At the moment we cannot detect drifting inside the kind=secret (i.e. external forces changing it). 

If we say that any target secret name content's are under our responsibility, we can create a hash of the data (ie. marshalling in json and doing md5 on the text), and store that hash inside an annotation on the secret. If on the reconcile loop annotation differs from the recalculated hash, then force the refresh (expected behaviour for ref=owner?)

If it's expected that the target secret can receive additional keys from an external operation, then we need to compare secret map which we do not have. To fix this we would need to amend the CRD and add an additional field to the Status (`lastSecretSynced`) where we would store a base64 encoded json containing the secret. This approach is potentially concerning from the security perspective. 

Your thoughts @moolen / @knelasevero ?

**Comment by alekc** [comment] 2021-09-01 11:26
So, to sum it up (I am thinking out loud here). 

In case of `creationPolicy: Owner` we can either:
- Just trigger the whole resync and fetch secrets from cloud provider
- Store the latest obtained secret data in the annotations (Or status, requires CRD change) on both ExternalSecret and kind=secret and perform full sync only in case they are different/missing
- Store the latest obtained data inside ExternalSecret (base64 encoded?) and use that to avoid any premature calling to cloud provider (requires Crd Change)

In case of `creationPolicy: Merge` we will likely have more often calls to the cloudprovider, and we can:
- perform full cycle on any changes to that secret (we do not know which fields are created by us)
- have a hybrid solution where we store the hash in one annotation and list of fields created by us in another, and validate it with the hash written in externalsecret
- Store the latest obtained data inside ExternalSecret (base64 encoded?) and use that to avoid any premature calling to cloud provide.

How precious are we in the current state of things about adding new fields to CRD?

**Comment by moolen** [comment] 2021-09-01 16:44
> adding new fields to CRD?

That's not a problem! We're consciously decided to stay in alpha to gather feedback and be free to add/remote fields to the `v1alpha1` CRD.

> creationPolicy: Owner

I think it would be best to perform a full cycle when the secret has been deleted: External state may have changed (e.g. `templateFrom` ConfigMap has changed). IMO we shouldn't store the plain text secret values in the status subresource.


> creationPolicy: Merge

We should know which fields were created by us through the field ownership mechanism (`secret.metadata.managedFields`). I think we should do a full cycle here too: diff existing keys with the ones from the provider and apply a patch to that resource. If nothing has changed we don't need to patch the resource.

**Comment by alekc** [comment] 2021-09-01 19:46
Ok, so just to confirm: on any change to existing configmap we are going
with a full cycle without storing the outcome in crd. If so, an amendment
to the docs will be in order starting that the refresh internal won't be
respected in case of changes to relate resources (I still need to verify
that a change in case of merged resource is triggered actually, chances are
they are not since we are not seeing the owner field. I am going by memory
and a bit drunk so I might be willing about this point)

**Comment by alekc** [comment] 2021-09-18 07:32
Fixed by https://github.com/external-secrets/external-secrets/pull/349

@moolen can we close this off?

**Closed** 2021-09-18 07:55 UTC

**Comment by jeffa5** [comment] 2021-09-18 12:09
Thanks!
