### ISSUE TITLE
Claim "iss" is invalid

### ISSUE THREAD

**Issue by xadereq** [external-secrets/external-secrets#508] opened 2021-11-29 16:45 UTC
**Describe the solution you'd like**
Kubernetes native authentication should work properly without flag `disable_iss_validation=true` in config.

**What is the added value?**
Up to date working configuration.

**Observations (Constraints, Context, etc):**

After creating auth config to Vault, which contains valid configuration (including issuer), controller can not fetch secret from Vault.

Config:
```
vault write auth/<redacted>/config \
        token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
        kubernetes_host="$KUBE_HOST" \
        kubernetes_ca_cert="$KUBE_CA_CERT" \
        issuer="https://kubernetes.default.svc.cluster.local"
```
and then after creating ExternalSecret kind:

```
{"level":"error","ts":1638199381.1249752,"logger":"controllers.ExternalSecret","msg":"could not get provider client","ExternalSecret":"external-secrets/vault-example","SecretStore":"/vault-backend","error":"error from Vault request: Error making API request.\n\nURL: POST https://<redacted>.com/v1/auth/<redacted>/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}
```

then after modifying same config but with `disable_iss_validation=true` value, everything is working as expected.
Whole cluster nodes are at version `v1.21.1`.

**Comment by knelasevero** [comment] 2021-11-29 17:46
@gusfcarvalho was this what you mentioned last week?

paging @ricardoptcosta @mcavoyk @cnmcavoy

**Comment by moolen** [comment] 2021-11-29 19:21
Hey @xadereq, the issue lies in the `Vault <-> Kubernetes` integration. I think you need to make sure that vault is able to validate the issuer, see the following issue for hints: https://github.com/external-secrets/kubernetes-external-secrets/issues/721#issuecomment-924896198. Depending on how you set up vault (in-/outside cluster) the one or the other fix will apply.

**Comment by gusfcarvalho** [comment] 2021-11-29 20:08
You can set the issuer with a command line adding issuer=<your-kubernetes-issuer>. For minikube the issuer is kubernetes.default.svc.cluster.local

This issue is not related to external-secrets, but really on which k8s/vault version you are using.

please keep in mind that issuer verification will be deprecated by hashicorp vault in the near future.

**Comment by xadereq** [comment] 2021-11-29 20:20
Thank you for your time investigating :)

Unfortunately, I've got vault injector (https://www.vaultproject.io/docs/platform/k8s/injector) set up on the same auth config and it's working flawlessly.
Are you pretty sure it's my fault?

My vault instances are outside cluster and integration is configured pretty much like here https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault#configure-kubernetes-authentication

**Comment by xadereq** [comment] 2021-11-30 08:47
Sure, I did it already (when configuring vault injector).

```
~: curl --silent http://127.0.0.1:8001/.well-known/openid-configuration | jq -r .issuer

https://kubernetes.default.svc.cluster.local
```

and configuration in vault auth:

```
vault read auth/<redacted>/config                                                                                                                                                           

Key                       Value
---                       -----
disable_iss_validation    true
disable_local_ca_jwt      false
issuer                    https://kubernetes.default.svc.cluster.local
kubernetes_ca_cert        -----BEGIN CERTIFICATE-----
<redacted_ca_cert>
-----END CERTIFICATE-----
kubernetes_host           https://<redacted>:443
pem_keys                  []
```
(disable_iss_validation is enabled now, and it's working)

**Comment by moolen** [comment] 2021-11-30 10:56
Ok great, that looks fine. Then, what's the content of the service account that you use to authenticate? Can you dump it into [jwt.io](https://jwt.io/) and paste its contents (`iss`, `sub`, `kubernetes.io/serviceaccount/*`)? How does that look like? Can you do the same for the token located at `/var/run/secrets/kubernetes.io/serviceaccount/token` in the external-secrets pod?

**Comment by gusfcarvalho** [comment] 2021-11-30 11:01
hi @xadereq ! Can you please share (with all redactions needed) your `SecretStore` configuration?

I've tried to do a mock cluster configuration using vault, and I was able to properly configure it (no errors, no disable jwt verification). Can you try that in a separate environment as well (not saying it isn't a bug, it's just to help out what the cause might be)?

```
vault auth enable kubernetes

k8s_host="$(kubectl exec vault-0 -n vault -- printenv | grep KUBERNETES_PORT_443_TCP_ADDR | cut -f 2- -d "=" | tr -d " ")"
k8s_port="443"            
k8s_cacert="$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode)"
secret_name="$(kubectl get serviceaccount vault -n vault -o go-template='{{ (index .secrets 0).name }}')"
tr_account_token="$(kubectl get secret ${secret_name} -n vault -o go-template='{{ .data.token }}' | base64 --decode)"

vault write auth/kubernetes/config token_reviewer_jwt="${tr_account_token}" kubernetes_host="https://${k8s_host}:${k8s_port}" kubernetes_ca_cert="${k8s_cacert}" issuer="https://kubernetes.default.svc.cluster.local"
```

The information @moolen said can also be obtained with:
```
kubectl get secrets <my-token-name> -n <my-namespace> -o jsonpath={.data.token} | base64 -d | cut -f2 -d . |  base64 -d
```

**Comment by xadereq** [comment] 2021-11-30 11:34
I'm really sorry for bothering all of you, I hope it won't be problem with my misconfiguration. Anyway maybe someone will find this conversation helpful :P

ClusterSecretStore configuration
```
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://<redacted>"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        namespace: vault
        name: tls-ca
        key: root-ca.pem
      auth:
        kubernetes:
          mountPath: "<redacted>" # it is path between auth/<path>/config
          role: "testapp"
          serviceAccountRef:
            name: "vault"
            namespace: "vault"
```

Role:
```
vault write auth/<redacted>/role/testapp \
        bound_service_account_names=test-app,vault \ # test-app SA is for vault-injector testing purposes
        bound_service_account_namespaces=vault \
        policies=test \
        ttl=24h
```

Output of @gusfcarvalho command (from the very end of comment):

```
{"iss":"kubernetes/serviceaccount","kubernetes.io/serviceaccount/namespace":"vault","kubernetes.io/serviceaccount/secret.name":"vault-token-<id>","kubernetes.io/serviceaccount/service-account.name":"vault","kubernetes.io/serviceaccount/service-account.uid":"059edb04-d5b2-4fae-b967-bfd4f40<last5digits>","sub":"system:serviceaccount:vault:vault"}
```

JWT token from inside external-secrets

```
{
  "aud": [
    "https://kubernetes.default.svc.cluster.local"
  ],
  "exp": 16698<last5digits>,
  "iat": 16382<last5digits>,
  "iss": "https://kubernetes.default.svc.cluster.local",
  "kubernetes.io": {
    "namespace": "vault",
    "pod": {
      "name": "external-secrets-7b77dc7d6-<last5digits>",
      "uid": "21c8ac23-5c6d-484e-8aa7-3b4a850<last5digits>"
    },
    "serviceaccount": {
      "name": "external-secrets",
      "uid": "5b4f955d-0a47-4a2b-a5ab-16c83bb<last5digits>"
    },
    "warnafter": 16382<last5digits>
  },
  "nbf": 16382<last5digits>,
  "sub": "system:serviceaccount:vault:external-secrets"
}
```

and from inside vault-agent-injector pod:
```
{
  "aud": [
    "https://kubernetes.default.svc.cluster.local"
  ],
  "exp": 16698<last5digits>,
  "iat": 16382<last5digits>,
  "iss": "https://kubernetes.default.svc.cluster.local",
  "kubernetes.io": {
    "namespace": "vault",
    "pod": {
      "name": "vault-agent-injector-5b8945bdfc-<last5digits>",
      "uid": "de34801e-8ea1-4aaa-9ab8-81e9851<last5digits>"
    },
    "serviceaccount": {
      "name": "vault-agent-injector",
      "uid": "cacd4119-4bc9-44ae-b677-6c99b3<last5digits>"
    },
    "warnafter": 16382<last5digits>
  },
  "nbf": 16382<last5digits>,
  "sub": "system:serviceaccount:vault:vault-agent-injector"
}
```

Again, kindly thank your for your support :)

**Comment by moolen** [comment] 2021-11-30 16:26
It looks like service accounts always get the `iss=kubernetes/serviceaccount` value. This seems to be the intended behavior in kube-controller-manager (see [here](https://github.com/kubernetes/kubernetes/blob/1d8966f4f92429fc1c1073d121dca1cc3f53974a/cmd/kube-controller-manager/app/controllermanager.go#L644): `LegacyIssuer` ).

ESO simply uses the jwt present in the referenced secret of the sa. We can not change the issuer here. We can tho i belive use the TokenProjection API to create a new token from the api-server (which should issue the token based on the `--service-account-issuer` flag) - we do that with the AWS provider already for auth via `AssumeRoleWithWebidentity`.

**Comment by moolen** [comment] 2021-12-01 22:12
@xadereq after reading this here https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/127 i think we don't need to fix this. This seems to be a design flaw in vault and is fixed with future vault versions.

> [...] token review API is the authority [and] there is no need to pre-validate the token issuer. 
Change the default value for `disable_iss_validation` to be true, and deprecate the `disable_iss_validation` and issuer configuration fields.

It's fine to disable issuer validation. It looks like you ran into the exact issue they fixed with this change. `iss` claim varies with Kubernetes 1.21+, see comment above.

**Closed by moolen** 2021-12-01 22:12 UTC
Labels: area/vault
