### ISSUE TITLE
Manage multiple properties of one 1Password entry

### ISSUE THREAD

**Issue by Zachu** [external-secrets/external-secrets#3130] opened 2024-02-09 09:35 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to manage multiple properties in one `onepassword` `PushSecret` manifest. My initial use case is to synchronize a [Kubernetes TLS Secret](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) into 1Password.

**Describe the solution you'd like**
With following manifests I would want to have one secret entry in 1Password having properties `foo` and `bar` set to the correct values:
```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: 1pass
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        Development: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: ismtip-1pass-token
            key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: foo-secret
stringData:
  foo: asd
  bar: das
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: foo-secret
spec:
  refreshInterval: 60s
  secretStoreRefs:
    - name: 1pass
      kind: SecretStore
  selector:
    secret:
      name: foo-secret
  data:
    - match:
        secretKey: foo
        remoteRef:
          remoteKey: test-foo-secret
          property: foo
    - match:
        secretKey: bar
        remoteRef:
          remoteKey: test-foo-secret
          property: bar
```

Instead I am getting two entries in 1Password with the exact same name `test-foo-secret` and after the second refresh the `PushSecret` goes into `Errored` state due to having two entries with the same name.

**Describe alternatives you've considered**
I tried separating these into two different entries (which isn't nice solution in my opinion) but ran across https://github.com/external-secrets/external-secrets/issues/3129 which is preventing me actually using the `onepassword` `PushSecret` completely :/

**Comment by onedr0p** [comment] 2024-02-09 14:03
Confirmed on my end...

```yaml
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: thanos
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: thanos-bucket-v2
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: thanos
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: thanos
```

```
  Normal   Synced   2s                   pushsecret  PushSecret synced successfully

  Warning  Errored  1s (x3 over 3s)      pushsecret  set secret failed: could not write remote ref AWS_SECRET_ACCESS_KEY to target secretstore onepassword-connect: error updating 1Password Item: status 400: Unable to update item "thanos" in Vault "xyz"
```

**Comment by onedr0p** [comment] 2024-02-09 14:06
Pinging @bthuilot since they are the author of the original PR. Maybe they can shed some insight.

**Comment by acelinkio** [comment] 2024-02-11 01:50
PushSecret functions and successfully created a secret in 1password, however the status is error.  

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: wildcard-production
  namespace: cilium-secrets
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: wildcard-production
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: tls.key
```

and throws the following failures relating to `token does not have permission to perform create on vault`.  This is using an Secrets Automation (https://developer.1password.com/docs/secrets-automation/) access token that has full access to my specified vault.

```log
{"level":"error","ts":1707615832.498571,"msg":"Reconciler error","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"wildcard-production","namespace":"cilium-secrets"},"namespace":"cilium-secrets","name":"wildcard-production","reconcileID":"0a8145f9-206e-414a-9b24-a76cb79e14f2","error":"could not write remote ref tls.crt to target secretstore 1password: error creating 1Password Item: status 403: Authorization: token does not have permission to perform create on vault h2cklnzoiixetlponscqvqcydm","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"}
```

**Comment by Zachu** [comment] 2024-02-12 09:30
Are you @acelinkio and @onedr0p affected by https://github.com/external-secrets/external-secrets/issues/3129 at all? In other words with your setup do you get two secrets in 1Password, one having the `tls.crt` property and one the `tls.key` (or `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`) or do you get more of them?

In my setup I got _two_ containing `tls.crt` and _two_ containing `tls.key`, in total 4 entries in 1Password. But weirdly it didn't seem to do that every time.

**Comment by bthuilot** [comment] 2024-03-03 16:21
okay sorry I didn't get a chance to look until now, but after doing some digging I think this is just a race condition that can be solved with a thread lock, like GCP Secrets Manager provider does [here](https://github.com/external-secrets/external-secrets/blob/0f6db5bd2235dd0b7114cf8049e6b69d1bd685ae/pkg/provider/gcp/secretmanager/client.go#L198-L202). Ill get started on a PR for it tag this issue when I open it

**Comment by onedr0p** [comment] 2024-03-06 14:03
Thanks for the updates @bthuilot, hope to see this landed soon 🙏🏼

**Comment by Skarlso** [comment] 2024-03-06 14:06
I'll throw up a PR and people can try and test it.

**Comment by onedr0p** [comment] 2024-03-06 14:27
I'll be able to test later today 💪

**Comment by Skarlso** [comment] 2024-03-08 10:31
I figured out what's wrong and you aren't going to like it.

It's happening too quickly. The locking doesn't do anything anywhere because 1password returns immediately with a success, but it didn't actually create the thing yet so when we IMMEDIATELY try again, it won't list the secret.

So the problem is 1password returning with a success even though it didn't yet create the thing actually. So the next data segment that we try to push will create a NEW entry since doesn't see the last entry.

The only "fix" I can think of is doing a GET on the item and waiting for it to actually exist before returning. That will help.

**Comment by Skarlso** [comment] 2024-03-08 13:17
I have a solution. It's not ideal, but it works. The problem is that all data items are sent one by one. Probably a bulk operation could be a lot better. But that would require rewriting the whole push secret logic.

**Comment by Skarlso** [comment] 2024-03-08 14:15
I already have a working solution, I'll update the PR.

**Comment by Skarlso** [comment] 2024-03-08 16:18
Added the updated PR. Feel free to test and review with `ghcr.io/skarlso/external-secrets:v0.9.13-44.gb4208003`.

**Closed** 2024-03-18 10:18 UTC
Labels: kind/feature
