### ISSUE TITLE
I amusing ArgoCD to build an app of apps and also using authentik for SSO.  in order for ArgoCD to work with SSO, the instructions specify adding a secret for the client into an existing secret created by ArgoCD.  in my kustomize, i can merge the secret using a secret generator.

### ISSUE THREAD

**Issue by Mamamau** [external-secrets/external-secrets#2644] opened 2023-08-23 14:19 UTC
I amusing ArgoCD to build an app of apps and also using authentik for SSO.  in order for ArgoCD to work with SSO, the instructions specify adding a secret for the client into an existing secret created by ArgoCD.  in my kustomize, i can merge the secret using a secret generator.  
```
secretGenerator:
- behavior: merge
  literals:
  - dex.authentik.clientSecret=MyClientSecret
  name: argocd-secret
`

**Comment by Mamamau** [comment] 2023-08-23 14:33
> I amusing ArgoCD to build an app of apps and also using authentik for SSO. in order for ArgoCD to work with SSO, the instructions specify adding a secret for the client into an existing secret created by ArgoCD. in my kustomize, i can merge the secret using a secret generator.
> 
> ```
> secretGenerator:
> - behavior: merge
>   literals:
>   - dex.authentik.clientSecret=MyClientSecret
>   name: argocd-secret
> ```
> 
> I was wondering if there is a way to merge the client secret into the existing argocd-secret from external-secrets so that the details are hidden like all my other secrets.
> 
> _Originally posted by @chupacabra71 in #2472_

**Comment by moolen** [comment] 2023-08-23 15:21
This seems to be a duplicate of https://github.com/external-secrets/external-secrets/discussions/2472

**Closed by moolen** 2023-08-23 15:21 UTC
