### ISSUE TITLE
Support Bitwarden Secrets Manager

### ISSUE THREAD

**Issue by fastlorenzo** [external-secrets/external-secrets#2661] opened 2023-08-28 13:58 UTC
**Is your feature request related to a problem? Please describe.**
Bitwarden Secrets Manager is currently not supported by external-secrets.

**Describe the solution you'd like**
Bitwarden recently released their Secrets Manager solution, which has better API support and is meant to be use as a secret store to be used programmatically. 

https://bitwarden.com/products/secrets-manager/

**Describe alternatives you've considered**
N/A

**Additional context**
Bitwarden SDK: https://github.com/bitwarden/sdk/

The following can be used to authenticate using a service account:

```
curl -X POST https://vault.bitwarden.com/identity/connect/token -H "content-type: application/x-www-form-urlencoded" --data 'scope=api.secrets&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&client_secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&grant_type=client_credentials'


{"access_token":"<TOKEN>","expires_in":3600,"token_type":"Bearer","scope":"api.secrets","encrypted_payload":"<PAYLOAD>"}
```

The resulting access token can be used to retrieve the server by ID:

```
curl https://vault.bitwarden.com/api/secrets/<SECRET_ID> -H 'Content-Type: application/json' -H "Authorization: Bearer <TOKEN>"


{"id":"<SECRET_ID>","organizationId":"<ORG_ID>","key":"<KEY>","value":"<VALUE>","note":"<NOTE>","creationDate":"2023-08-28T12:32:50.6798356Z","revisionDate":"2023-08-28T12:32:50.6798357Z","projects":[{"id":"<PROJECT_ID>","name":"<PROJECT_NAME>"}],"read":true,"write":false,"object":"secret"}
```

Please note that the returned secret looks encrypted, I still need to figure out how to decrypt it.

However, another option would be to use the `bws secret get <SECRET_ID> -t <SERVICE_ACCOUNT_SECRET>` command, which returns the secret in clear text.

**Comment by fastlorenzo** [comment] 2023-08-28 14:03
[api.json.txt](https://github.com/external-secrets/external-secrets/files/12455184/api.json.txt)

Attached the swagger file I've extracted from latest master of Bitwarden Server (if it can be of any use)

**Comment by larivierec** [comment] 2023-09-08 14:41
oh nice, i didn't see there was an api attached to bitwarden, this should be possible now :)

**Comment by fastlorenzo** [comment] 2023-09-18 21:37
> the other thing would be the bitwarden/sdk would ideally have to expose a `golang` client otherwise, it would have to re-written

I think this should do it once merged :smile: https://github.com/bitwarden/sdk/pull/218

**Comment by logan-hcg** [comment] 2023-12-02 03:35
Looks like the golang SDK was just merged :crossed_fingers:

**Comment by fastlorenzo** [comment] 2023-12-03 19:56
@larivierec are you taking this up with the bitwarden golang SDK?
I can help but I'm not a pro writing in golang :smile:

**Comment by jenrik** [comment] 2024-01-23 21:12
perhaps a webhook based integration might be a better starting point for now, we can avoid bloating external-secrets by shipping bitwarden secret manager related things in a separate container

**Comment by larivierec** [comment] 2024-01-23 21:18
Yeah, after seeing the integration I do believe this is a better avenue

I was expecting a simple REST api or something

**Comment by kevindurb** [comment] 2024-03-28 17:06
Any movement on this? Any way that I could help? Would love to switch from the cli api to bw secrets manager if only to have the ability to not expose my entire vault to my kubernetes cluster 😬

**Comment by jenrik** [comment] 2024-06-03 11:58
as an alternative Bitwarden have launched their own operator, https://preview.bitwarden.com/help/helm-integration/

**Comment by fastlorenzo** [comment] 2024-06-08 19:56
> as an alternative Bitwarden have launched their own operator, https://preview.bitwarden.com/help/helm-integration/

@jenrik the link you've provided seems down already

**Comment by Skarlso** [comment] 2024-06-09 15:32
I'll take this one.

**Comment by Skarlso** [comment] 2024-06-09 15:44
This looks like a Go SDK that I can use just fine: https://github.com/bitwarden/sdk-go

**Comment by logan-hcg** [comment] 2024-06-09 15:53
@Skarlso I think this uses the rust library still?  

https://github.com/bitwarden/sdk-go/blob/main/internal/cinterface/bitwarden_library.go

This the concerns about size, etc:
https://github.com/external-secrets/external-secrets/issues/2661#issuecomment-1840943345

**Comment by Skarlso** [comment] 2024-06-09 15:58
Yeah, I gathered that. It looked like just a mirror of some sorts.

**Comment by Skarlso** [comment] 2024-06-09 16:16
Honestly, it looks like, I'll just have to whip up a rudimentary REST API and done. I would rather do that, than use CGO and the rust commands.

**Comment by Skarlso** [comment] 2024-06-09 16:40
Ugh, I'm getting invalid grant. 🤔

**Comment by Skarlso** [comment] 2024-06-09 16:46
Ahhh... you aren't supposed to use the public API with a user token 🤔

**Comment by logan-hcg** [comment] 2024-06-09 16:48
Which rest API are you using?

**Comment by Skarlso** [comment] 2024-06-09 16:49
https://vault.bitwarden.com/identity/connect/token

**Comment by Skarlso** [comment] 2024-06-10 07:42
Okay, finally got the API working with right device type and stuff.

```
curl -X POST https://identity.bitwarden.com/connect/token \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "grant_type=client_credentials" \
     -d "client_id=${BITWARDEN_CLIENT_ID}" \
     -d "client_secret=${BTIWARDEN_CLIENT_SECRET}" \
     -d "scope=api" \
     -d "deviceIdentifier=123e4567-e89b-12d3-a456-426614174000" \
     -d "deviceName=laptop" \
     -d "deviceType=5"
```

Basically, identifier is just a UUID and deviceName and type will be external-secrets and the OS.

Encryption and Decryption are a bit pain in the arse, but it's okay. The login above contains the key and the private key.

It's not that easy doing all of this, because there is literally no documentation. :D They don't really want you to write your own thing. I tried running the rust lib they have but it's super attrocious. :D So not going to do that haha.

**Comment by Skarlso** [comment] 2024-06-10 11:55
Hmmm. This is getting problematic. The Encryption and Decryption is working, but I literally replicate what they are doing in the code. It's problematic, because if they change the algorithm somehow, this thing will no longer work and it will be a nightmare to keep up-to-date with new ways of encryption.

I'm a bit concerned that I'm basically creating a new Go library. And even though I hate having to use CGO and the Rust implementation I fear there is no way around that unless we "compete" with their Go library. 😢

**Comment by Skarlso** [comment] 2024-06-10 12:03
That said, it's highly unlikely that the encryption method changes...

**Comment by logan-hcg** [comment] 2024-06-10 12:06
Yeah, that would be a lot of (ongoing) work.  

What if instead of integrating directly (and thus making the base image fat), we instead implement a sidecar container that exposes a very simple REST api (something like `GET /secret/<secret_id>`), and this sidecar container uses the official Go SDK (and rust library)?  And then use the generic webhook to fetch the values.

**Comment by Skarlso** [comment] 2024-06-10 12:10
That would be problematic during store configuration changes. Like, you'd have to have tight control over the side-car and re-create it every time the configuration or the store changes, because of a namespace update, or filter update, or anything really that could change the way of accessing the bitwarden service. 🤔

**Comment by Skarlso** [comment] 2024-06-10 12:12
Oh sorry, not when the store changes, but when the store gets deleted, the sidecar needs to disappear or reappear if a new store is created.

**Comment by logan-hcg** [comment] 2024-06-10 12:16
@Skarlso I'm not sure I understand the issue/concern?   From the External Secrets Operator perspective, it would work like any "external webhook".

**Comment by Skarlso** [comment] 2024-06-10 12:18
The service needs to be running in a separate container either inside the pod, or outside of it. If there is no bitwarden store, there shouldn't be any service running anywhere. If there is, it needs to be started.

**Comment by logan-hcg** [comment] 2024-06-10 12:22
ah, yes, you are correct.  It would be a separate step, or be a configuration value that needs to be enabled in the helm chart.  Similar to `certController` (https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L404), where it is a separate component that is run in concert with the "standard" operator.

**Comment by Skarlso** [comment] 2024-06-10 12:24
Ah, I see what you mean as well. I thought it would be a dynamic component. :D But yeah, so basically, if you know you are going to require bitwarden you'll just launch that separate service straight away.

That's not a bad idea. :D

**Comment by Skarlso** [comment] 2024-06-10 12:34
*problem -> project. :) I meant I'm relatively new to external-secrets. :)

**Comment by Skarlso** [comment] 2024-06-10 19:33
BTW, found their operator https://github.com/bitwarden/sm-kubernetes

**Comment by Skarlso** [comment] 2024-06-10 20:01
This is where the wrapper will live: https://github.com/external-secrets/bitwarden-sdk-server

**Comment by Skarlso** [comment] 2024-06-12 13:01
It _looks_ like we can get away with just using https://github.com/bitwarden/sdk-go since it contains the pre-built libraries. So no need to do anything with the SDK. Just include this project and use
```
CGO_LDFLAGS="-framework CoreFoundation" CGO_ENABLED=1 go build main.go
```

**Comment by Skarlso** [comment] 2024-06-12 13:02
That said................. I'm debating the following. Does it REALLY matter that we add a 140 or so MB to the image size as opposed to frigging writing an managing a separate entire project with REST api and launching a separate process in a POD and making sure that runs, etc, etc...?

**Comment by Skarlso** [comment] 2024-06-12 13:26
Never mind. ESO supports way more architectures than what bitwarden would support. :D So that settles this debate. :D

**Comment by Skarlso** [comment] 2024-06-12 13:31
I'll keep on building out the REST api. It's in good shapes already. It also has the added benefit I guess that it can be versioned outside of ESO's lifecycle.

**Comment by larivierec** [comment] 2024-06-12 14:45
So just to confirm, how this will work is we'll need to run the `bitwarden-sdk-server` + `external-secrets` with the bitwarden client and external-secrets binary will contain the bws-sdk with the library ?

**Comment by Skarlso** [comment] 2024-06-12 14:51
Yep, pretty much that. The bitwarden-sdk-server will expose an HTTPS API that ESO will call to do things.

Then, when installing ESO you know beforehand that you'll require bitwarden, you can flip a switch to install `bitwarden-sdk-server` as well.

**Comment by larivierec** [comment] 2024-06-12 14:58
Oh that's neat, didn't know that was a possibility! Thanks for the explanation

**Comment by joryirving** [comment] 2024-06-12 15:10
Just as an FYI - I use a custom version with ESO. Not sure if this makes a decent kick off point:
[bws-cache](https://github.com/rippleFCL/bws-cache)
[example deployment](https://github.com/joryirving/home-ops/blob/main/kubernetes/utility/apps/external-secrets/external-secrets/bitwarden-secrets-manager/helmrelease.yaml)
[example secret](https://github.com/joryirving/home-ops/blob/main/kubernetes/utility/apps/default/cloudflare-ddns/app/externalsecret.yaml)

**Comment by logan-hcg** [comment] 2024-06-17 11:51
@Skarlso this is great news!

One question: how are the bitwarden service account tokens handled?  I could see two different ways:
1. The `bitwarden-sdk-server` is a transparent proxy, so that the token is on the `SecretStore` and gets passed to the `bitwarden-sdk-server` to "pull through" the bitwarden secret; or
2. The `SecretStore` has credentials to talk to the `bitwarden-sdk-server`, and the `bitwarden-sdk-server` is configured with the bitwarden service account token to pull/cache from the Bitwarden API

Let me know if this question isn't clear... :smiley:

**Comment by Skarlso** [comment] 2024-06-17 11:53
Everything is going through eso. So no extra config or anything needs to be provided for the server. So yeah it's pull through. But eso will handle that seamlessly. From the user's perspective other than enabling the server during helm install with `--set Bitwarden-server=enabled` or something nothing will change. They will just create the secret store with necessary info and done.

**Comment by logan-hcg** [comment] 2024-06-17 12:00
@Skarlso that is amazing.  Thanks for working on this!

**Comment by Skarlso** [comment] 2024-06-17 19:36
```
{"creationDate":"2024-06-09T16:57:55.958293900Z","id":"<id>","key":"test","note":"test","organizationId":"<id>","projectId":"<id>","revisionDate":"2024-06-09T16:57:55.958294Z","value":"test"}
```

FINALLY. It's working.

**Comment by joryirving** [comment] 2024-06-19 14:01
Is there a way to pull based on the secret name, rather than the key?

**Comment by Skarlso** [comment] 2024-06-19 14:05
Yes I will add something like that somehow.. Right now it's super basic. :) Using the key of the secret is rather inconvenient HOWEVER... The problem is that bitwarden actually allows multiple secrets with the same name. :)

Do you see the problem with that? :D If we try retrieving by name... We have no idea which secret to retrieve. Also, there is no "nice" way of doing this other than listing ALL secrets and choose one. Or error if there is more than one secret with the same name. 🤷

**Comment by Skarlso** [comment] 2024-06-19 14:05
<img width="320" alt="Screenshot 2024-06-19 at 16 05 44" src="https://github.com/external-secrets/external-secrets/assets/182850/8a017ad1-a5c9-4513-94c2-264d8415f45c">

**Comment by joryirving** [comment] 2024-06-19 14:10
I currently do it that was with [bws-cache](https://github.com/rippleFCL/bws-cache).
I do understand the risk that you're stating.

![image](https://github.com/external-secrets/external-secrets/assets/46251616/ea2fbc62-69f7-4d20-86ce-eb8ddfbb159b)

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name test-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        TEST_VAR: '{{ key1 }}'
  dataFrom:
  - extract:
      key: test1
```

**Comment by Skarlso** [comment] 2024-06-19 14:14
I would rather not that honestly. It's super dangerous.

**Comment by logan-hcg** [comment] 2024-06-19 14:58
My preference would be to get a simpler implementation released faster, so one that only allows specifying the uuid.  It wouldn't be perfect, but it would at least be usable.


Plus by uuid seems to be "the way" that bitwarden expects it to be used, even though that isn't very user friendly: https://community.bitwarden.com/t/cli-get-a-secret-by-its-key/54253/3

**Comment by Skarlso** [comment] 2024-06-19 15:04
Absolutely agreed on that.

I'll work on getting something to work then we can iterate on it.

**Comment by mirceanton** [comment] 2024-06-19 22:15
FWIW, I agree with @joryirving 

Referencing secrets by name, instead of ID, and then just throwing some error if there are multiple secrets with the same name found makes the most sense to me

**Comment by Skarlso** [comment] 2024-06-20 05:46
Sure. The only problem is that I have one key to work with. :D The SecretKey or a property. But the key is mandatory.

So what I could do is detect if the key is a UUID and based on that do a lookup or a search for it.

The GetSecret part doesn't have a Metadata section so it's not like I can push in extra data to do something like GetByName or GetByID..

**Comment by Skarlso** [comment] 2024-06-20 05:52
Unless... Another id would be that the Store defines AT LEAST the Organization. Which would mean that the ProjectID could indeed be the property. 🤔

**Comment by Skarlso** [comment] 2024-06-20 05:54
Hmm... that could actually work. So the SecretStore itself will contain the Organization ID. And thus there will be a store / organization which makes sense. You don't want to have a single store and then just mock about with the org ID everywhere.

I think that could work. And then the property is actually the project ID which can further restrict where to look for a secret.

I'll play around with this and see how it goes.

**Comment by Skarlso** [comment] 2024-06-20 06:26
Okay, so how this will work for PushSecret and GetSecret is that 

- name, projectID, organizationID and value equal, we won't push it again.
- name, projectID, organizationID and ONLY the value does not equal we update
- any of the above isn't true, we create the secret

For Get:

- if name is a uuid get the secret
- if name is NOT a uuid Property is mandatory that defines the projectID to look for
- if name + projectId matches, we return that secret
- if more than one name exists for the same projectId within the same organization we error
-

**Comment by Skarlso** [comment] 2024-06-20 16:06
Most of the things are working now. Just adding a bunch of tests and then... it's basically done. :D

**Comment by Skarlso** [comment] 2024-06-21 08:56
The PR is ready for review, but I'm still running tests. :)

**Comment by Skarlso** [comment] 2024-06-21 09:26
Everything is working it seems. I'm sure there are some bugs in there.. but let's see.

Now it's up to the maintainers to give some feedback and PR reviews of which I'm sure there will be plenty. :D

But for now, I'm done. :)

**Comment by larivierec** [comment] 2024-06-21 12:32
Cool! Would it be possible to link the PR?

**Comment by Skarlso** [comment] 2024-06-21 12:44
It is linked, if you scroll up a bit. :)

**Comment by Skarlso** [comment] 2024-06-21 12:45
https://github.com/external-secrets/external-secrets/pull/3603

**Comment by larivierec** [comment] 2024-06-21 14:12
My bad thanks :)

**Comment by Skarlso** [comment] 2024-06-22 09:00
How do you peeps feel if the store is per project instead of just organisation?

So org/proj.

That would ease the external secret config. And the idea is that an organisation would have projects per teams and it would feel vary bad if all of them would use a single store and then prefix the secret with the project. 🧐

**Comment by mirceanton** [comment] 2024-06-22 09:06
Imho that is fine. I can, for example, create an org for my Homelab and then 1 project per cluster, right? That means each cluster will have its own independent secret store and I'll be able to group all of them under an org.

If my understanding is correct, then that sounds like a good solution!

**Comment by Skarlso** [comment] 2024-06-22 16:23
That's true. A single access token can have multiple project accesses. But that's fine right? A team can still have access to prod and dev projects using a single token or they would have acccess to their dev environment but not to the other teams dev environment that requires a diffierent token.

The organisation would own the machine account and distribute tokens as desired by an admin.

**Comment by Skarlso** [comment] 2024-06-22 17:28
> Imho that is fine. I can, for example, create an org for my Homelab and then 1 project per cluster, right? That means each cluster will have its own independent secret store and I'll be able to group all of them under an org.
> 
> If my understanding is correct, then that sounds like a good solution!

Yep, that is the intended usage here.

**Comment by Skarlso** [comment] 2024-06-22 17:45
We'll go with that approach and see how it goes. If it's too unwieldily or people complain enough, we can always adjust it. :)

**Closed** 2024-06-28 04:04 UTC
Labels: kind/feature

**Comment by Skarlso** [comment] 2024-06-28 04:29
Bitwarden support has been added. Thank you very much for everyone involved. Please report any problems as a separate issue and include Bitwarden in the title. Please also ping me in the issue.

Thanks and thank you for the ESO team's support and reviews and conversations!
