### ISSUE TITLE
GitHub secrets provider

### ISSUE THREAD

**Issue by zs-dima** [external-secrets/external-secrets#2973] opened 2023-12-23 16:07 UTC
Would be nice to add GitHub secrets provider, to be able to use GitHub secrets.

**Comment by moolen** [comment] 2023-12-23 20:53
Hey, thank you for your interest! This is a duplicate of #1727, there's a draft PR open for it in #2843. Going to close this issue.

**Closed by moolen** 2023-12-23 20:53 UTC
Labels: kind/feature
