### ISSUE TITLE
provide a way to define a template that can generate the resulting secret keys dynamically

### ISSUE THREAD

**Issue by mmerickel** [external-secrets/external-secrets#1068] opened 2022-05-01 23:25 UTC
**Describe the solution you'd like**

Extend the `ExternalSecretTemplate` with a `dataTemplate` argument that defines a full template for the secret that is rendered prior to knowing what the keys are so that logic can be used in the resulting values to determine what keys to render and how.

**What is the added value?**

Currently every ExternalSecret must know up front exactly what keys will be rendered, which limits using the remote secret values as a config for the resulting secret. For example I want to query the value of a secret for ArgoCD and render out a different format based on whether it's a helm secret or a git secret, or whether it's username/password or just an ssh private key.

**Give us examples of the outcome**

```yaml
dataTemplate: |
  url: {{ .url }}
  {{ if hasPrefix .url "oci://" }}
  enableOCI: "true"
  {{ end }}
  {{ if hasKey . "username" }}
  username: {{ .username }}
  {{ end }}
  {{ if hasKey . "sshPrivateKey" }}
  sshPrivateKey: {{ .sshPrivateKey }}
  {{ end }}
  {{ if hasKey . "password" }}
  password: {{ .password }}
  {{ end }}
```

**Observations (Constraints, Context, etc):**

Don't see any problems with this - it's just a gap currently in the templating abilities of external-secrets. The code doesn't seem like it would have trouble supporting it as it's regularly passing around a `tplMap`, and this template should be used as the source for that variable. It should be rendered first, parsed as a key/value map, written into `tplMap`, then anything from `templateFrom` and `data` should override values in it.

**Comment by gusfcarvalho** [comment] 2022-05-02 18:11
You still would need to know the minimum structure of your secret anyways, right?

I would just like to add that this feature would be better handled if it was encapsulated to a configMap key. Having an inline `dataTemplate` definition for the whole secret will be un-readable, IMO.

Also IMO, this should replace `data` whenever available. The new template will define how the whole secret would be rendered, I don't see how having it re-templated again would make any difference here as the "target keys" (username, password, uri) still needs to be known prior to the creation of the template.

**Comment by moolen** [comment] 2022-05-02 18:36
I think this is a duplicate of https://github.com/external-secrets/external-secrets/issues/464 and closely related to #975 :thinking:

**Comment by mmerickel** [comment] 2022-05-02 19:01
#975 says touches on this request as out of scope but I think I agree that #464 is related albeit with a different proposed solution.

**Comment by mmerickel** [comment] 2022-05-02 23:32
@gusfcarvalho I'm not sure what you mean by minimum structure. There's a world where you could simply plop the blob from the remote store into your template and be done with it - having the entire structure be defined elsewhere. What I mean is define a secret with a json string in it, and have the template just be something like `{{ . }}`. I'm not saying it's a good idea but I don't know why I shouldn't be allowed to do it if I trust the remote source.

**Comment by mmerickel** [comment] 2022-05-02 23:35
> Also IMO, this should replace data whenever available.

@gusfcarvalho I disagree - the data area is the most specific part of a template and thus should have the highest precedence. It should be `existingSecret -> dataTemplate -> templateFrom -> data` from left to right.

**Comment by gusfcarvalho** [comment] 2022-05-04 09:07
My concern here would be the following:
```
dataTemplate: |
  url: {{ .url }}
  {{ if hasPrefix .url "oci://" }}
  enableOCI: "true"
  {{ end }}
  {{ if hasKey . "username" }}
  username: {{ .username }}
  {{ end }}
  {{ if hasKey . "sshPrivateKey" }}
  sshPrivateKey: {{ .sshPrivateKey }}
  {{ end }}
  {{ if hasKey . "password" }}
  password: {{ .password }}
  {{ end }}
data:
  randomKey: {{ .username }}
  url: "oci:// {{ .myUrl }}"
  password: "hey"
```
What do you believe it would be the expected outcome? For me, this is something we simply should not allow, even though it would be a valid logical ordering, it is just confusing. Either we should stop at validation level (no `dataTemplate` and `data` in the same ExternalSecret) or at logic level (whenever `data` is available we ignore `dataTemplate` and use `data` instead, or the other way around. I honestly think if people are using both of them, the one that is less relevant is `data`, as `dataTemplate` is also manipulating keys).

This is indeed a duplicate from #464. @mmerickel do you mind if we close this one and track it down on there?

**Closed** 2022-12-05 22:54 UTC
Labels: duplicate, area/templating
