### ISSUE TITLE
External secrets no longer sets the ExternalSecret labels in the secret by default

### ISSUE THREAD

**Issue by tete17** [external-secrets/external-secrets#2790] opened 2023-10-16 16:27 UTC
**Describe the bug**
I used to relay simply set the labels I wanted in the ExternalSecret resource and that would propagate to the Secret. This is useful for example for ArgoCD that relays on some labels to exists to detect the secret.

**To Reproduce**
1. provide all relevant manifests
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-monorepo
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        type: git
        url: REDACTED
        username: '{{ .username }}'
        password: '{{ .password }}'
  dataFrom:
    - extract:
        key: development/argocd/gitlab
```

2. provide the Kubernetes and ESO version
 * k8s: 1.27.3
 * ESO: 0.9.6

**Expected behavior**
I expect the label to appear in the underlying secret instead I have the following
```yaml
apiVersion: v1
data:
  password: REDACTED
  type: REDACTED
  url: REDACTED
  username: REDACTED
immutable: false
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: c280f8234c33cc7036331c934443c6d3
  creationTimestamp: "2023-10-16T16:18:12Z"
  labels:
    reconcile.external-secrets.io/created-by: 0846843371d070ed27050fa588a0ae8d
  name: argocd-monorepo
  namespace: argocd
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: argocd-monorepo
    uid: daa02da7-5d01-472a-85d0-7d2dca76f99d
  resourceVersion: "541191986"
  uid: ac777eed-6d3f-47c8-afa7-47bbc5ffdc23
type: Opaque
```

As you can see the label `argocd.argoproj.io/secret-type: repository` is nowhere to be found

**Comment by rakrueger** [comment] 2023-10-17 15:17
Hi @tete17, I notice two things:

- You mentioned you want to create annotations but in the ExternalSecret you set a label
- When using a template, you can set labels and annotations within the template, you can test to use this option instead:

```
# Specify a blueprint for the resulting Kind=Secret
    template:
      type: kubernetes.io/dockerconfigjson # or TLS...

      metadata:
        annotations: {}
        labels: {}

      # Use inline templates to construct your desired config file that contains your secret
      data:
        config.yml: |
          database:
            connection:
```

**Comment by tete17** [comment] 2023-10-19 09:59
Hi @rakrueger you are right indeed I meant to say labels not annotations, I have edited the issue.

I am aware of the fact I can override the labels using the template and in fact it is my workaround.
I was under the impression that before I used to be able to simply add the labels to the external secrets and it propagate them by default, the same way if not set otherwise the name gets propagated.

I wonder if that old behaviour was never intended or it was accidentally removed

**Comment by shuheiktgw** [comment] 2023-10-19 22:56
Thank you for reporting the issue, @tete17! 👋  Let me check what is going on.

**Comment by shuheiktgw** [comment] 2023-10-19 23:55
Hi, I've checked our current implementation, and it turned out that if you use the template, metadata on the external secret is ignored. 

https://github.com/external-secrets/external-secrets/blob/719e8b1c82c81cd09c221776842f2dabcd335a2c/pkg/controllers/externalsecret/externalsecret_controller_template.go#L204-L217

I also confirmed it worked fine, meaning metadata on the external secrets appeared on a child secret if you didn't set the template. I'm closing this issue for now, since this's been how it works, but please feel free to reopen it if you have any other concerns.

**Closed by shuheiktgw** 2023-10-19 23:55 UTC
Labels: kind/bug
