### ISSUE TITLE
Ability to create external-secret custom resources before the external-secrets deployment is live on the cluster

### ISSUE THREAD

**Issue by psimms-r7** [external-secrets/external-secrets#1290] opened 2022-06-23 16:46 UTC
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

The ability to create external-secret custom resources before the external-secrets deployment is live on the cluster.  So we can create secret stores and secrets using terraform before the deployment is live, allowing the helm release to be handled post terraform, for example using argocd.

Following the example in the reference below, we can use terraform resource "kubectl_manifest" to create external-secrets resources however it now appears to be failing due to a webhook validation, is there a way to disable this at this stage?

Terraform example
```
resource "helm_release" "external_secrets_custom_resource_definition" { // Custom helm chart to deploy the external-secrets crds
  name             = "external-secrets-crd"
  chart            = "${path.module}/crds"
  namespace        = "external-secrets"
  create_namespace = true
  version          = "1.0.0"
}

resource "kubectl_manifest" "external_secrets_cluster_store" {
  depends_on = [
    helm_release.external_secrets_custom_resource_definition
  ]
  yaml_body = <<YAML
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ${var.cluster_name}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${data.aws_region.current.name}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
YAML
}
```

Error
```
│ Error: cluster-dev-1 failed to run apply: error when creating "/var/folders/62/mw1prxy56jb3zhn9bg8y2kf40000gq/T/724096788kubectl_manifest.yaml": Internal error occurred: failed calling webhook "validate.clustersecretstore.external-secrets.io": Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-clustersecretstore?timeout=5s": service "external-secrets-webhook" not found
│ 
│   with module.external-secrets.kubectl_manifest.external_secrets_cluster_store,
│   on ../submodules/external-secrets/external-secrets.tf line 10, in resource "kubectl_manifest" "external_secrets_cluster_store":
│   10: resource "kubectl_manifest" "external_secrets_cluster_store" 
```

Reference
https://medium.com/@danieljimgarcia/dont-use-the-terraform-kubernetes-manifest-resource-6c7ff4fe629a

**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".

We can pre configure the secret store and secrets before the external-secrets operator is live on the cluster, meaning we don't need to break up the deployment flow of terraform setting up the cluster and the helm deployments through argocd

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

**Comment by albertollamaso** [comment] 2022-06-24 08:00
@psimms-r7 it seems you are running `v1alpha1` of the ESO and by trying to apply a `v1beta1` it is calling a conversion webhook that is required.

**Comment by gusfcarvalho** [comment] 2022-06-24 17:08
Actually I think the root cause here is the ValidatingWebhook. If you are installing ESO from helm charts, what we normally recommend is to configure the `--wait` behavior on it - but then who's installing the ValidatingWebhook is argo, not terraform.

If you really need to have both agents available in the cluster, you will need to find out a solution to control whether the `ValidatingWebhookConfiguration` are already in place before trying to create any terraform resources that depend on it. Once they are up, you need to wait for the helm chart installation in order to properly use it. One option, I guess, is to control yourself the ValidatingWebhookConfiguration installation. This should allow you to install any es versions and then configure it at a later time.


Altough we strongly advise you not to, you can always disable the Webhook functionality by setting `--set certController.create =false --set webhook.create = false`in your helm charts. The risk here is that the validating webhook prevents you from creating some crazy configuration which can be potentially harmful.

**Comment by gusfcarvalho** [comment] 2022-06-24 17:15
Regarding to ESO itself, I'm not sure what we can do on our side to help you with this issue. 
The root cause of it is that you're using two different agents (terraform and Argo) to install ESO. ESO is compliant if you use terraform `helm_release` or `kubernetes` or if you use argo. We also provide a `make manifests` so users can customize their own installation if the defaults don't work (which I think is the way you need to go here).

**Comment by psimms-r7** [comment] 2022-06-27 09:51
Thanks you for all the replies

It seems ESO was lingering around somehow in the cluster and causing this, this was just a dev cluster so testing/deploying it etc. so ESO was deployed to it few times and in turn removed, in this instance I was under the impression everything was removed from the cluster, I fully removed all resources and namespace for external secrets, but was getting the error described.  I then destroyed the whole cluster and tested again and confirmed all worked as expected with the initial terraform setup then argocd deploying ESO.

So it seems something was lingering around from a previous deployment causing conflicts here

**Comment by pm3ndoza** [comment] 2022-09-02 22:42
Hello guys, i have a similar issue, But im not understand what do you mean when you say ESO. 
Could you help me to understand that. 
This is executed inside a aws ec2 (was deployed with terraform) whit all the correct roles, this is an intermittent issue, that i have.  

`Error from server (InternalError): error when creating "ms-test-secrets.yaml": Internal error occurred: conversion webhook for external-secrets.io/v1alpha1, Kind=ExternalSecret failed: Post "https://external-secrets-webhook.external-secrets.svc:443/convert?timeout=30s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by moolen** [comment] 2022-09-03 08:17
@pm3ndoza you probably have an issue with security groups. You must allow access to the webhook service from the EKS control plane. There is a closed issue, please use the search, that will help you. IIRC you must set the webhook service port to 10250 or change the security group.

ESO is just short for external secrets operator.

Closing this issue as it seems resolved. Feel free to comment/reopen

**Closed by moolen** 2022-09-03 08:17 UTC
Labels: triage/support, area/charts
