### ISSUE TITLE
certificate error in webhook  http: TLS handshake error from xx.xx.xx.xx: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by amohamedhey** [external-secrets/external-secrets#1351] opened 2022-07-12 10:06 UTC
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 
fix certificate error in webhook  http: TLS handshake error from xx.xx.xx.xx: remote error: tls: bad certificate

**What is the added value?**
We'll get a fully supported solution for AWS EKS.

Observations (Constraints, Context, etc):

Context: 
I have disable `cert-controller` coming with external-secrets helm chart and use the `cert-manager`. I have installed it in EKS cluster.
I am getting error in the webhook:
`http: TLS handshake error from xx.xx.xx.xx: remote error: tls: bad certificate`
I set `webhook.port` to `9443` and default one `10250` 
I annotate the ValidatingWebhookConfiguration and CRD(s) with `cert-manager.io/inject-ca-from: `
I set `duration: 87600h0m0s` to the certificate 

EKS Version: 1.21
External Secrets Helm Chart Version: 0.5.7

Thanks for your support

**Comment by gusfcarvalho** [comment] 2022-07-12 12:16
Hi @amohamedhey ! I'm sorry, but we are missing some information here. Where did you see this error? Are you running on fargate? Can you  share your annotations, please?

this might be a duplicate of https://github.com/external-secrets/external-secrets/issues/1249

**Comment by amohamedhey** [comment] 2022-07-12 12:47
the error generated from external-secrets webhook pod 
We are running EKS on EC2
the annotation:
`cert-manager.io/inject-ca-from: kube-system/webhook-external-secrets-certificate`

**Comment by gusfcarvalho** [comment] 2022-07-12 12:54
can you share the webhook pod log, please?

**Closed as completed** 2022-07-12 13:52 UTC
Labels: triage/needs-information
