### ISSUE TITLE
GCP Workload Identity on SecretStore not working

### ISSUE THREAD

**Issue by nokernel** [external-secrets/external-secrets#546] opened 2021-12-23 19:33 UTC
**Describe the solution you'd like**
GCP Workload Identity on SecretStore not working. Using helm chart version 0.3.10 to install.

Following the [doc here](https://external-secrets.io/provider-google-secrets-manager/#using-service-accounts-directly)

**Give us examples of the outcome**

Ability to reference Google service account on SecretStore.

**Observations (Constraints, Context, etc):**

This manifest fails to deploy
```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: mystore
spec:
  provider:
    gcpsm:
      projectID: my-project-id
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: myCluster
          serviceAccountRef:
            name: service-account-name
```

With error
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(SecretStore.spec.provider.gcpsm.auth): unknown field "workloadIdentity" in io.external-secrets.v1alpha1.SecretStore.spec.provider.gcpsm.auth, ValidationError(SecretStore.spec.provider.gcpsm.auth): missing required field "secretRef" in io.external-secrets.v1alpha1.SecretStore.spec.provider.gcpsm.auth]
```

**Comment by knelasevero** [comment] 2021-12-27 10:23
Sorry, documentation right now is published every time we merge to main, even if we did not release stuff that docs are talking about. Will try to fix that next year when we have more time.

But, yeah, next release that will be available :)

**Comment by gusfcarvalho** [comment] 2022-01-07 12:29
@nokernel can you confirm that using version 0.3.11 the issue is gone?

**Comment by onsails** [comment] 2022-01-08 19:23
I can confirm it works on 0.3.11

**Comment by knelasevero** [comment] 2022-01-09 14:08
Closing this one. Feel free to report back and re-open :)

**Closed by knelasevero** 2022-01-09 14:08 UTC

**Comment by nokernel** [comment] 2022-01-10 14:04
Got past that error now with v0.3.11 thank you that was quick :+1:
