### ISSUE TITLE
Kubernetes provider with 'binary' secret producing gibberish

### ISSUE THREAD

**Issue by gerrieg** [external-secrets/external-secrets#2673] opened 2023-09-01 10:42 UTC
**Describe the bug**
I have a namespace local-vault with my secrets and I use ExternalSecrets in all namespaces to select the secrets. This worked great up to and including version 0.8.1.
I also have a secret with the java cacerts file. Since version 0.8.2, the ExternalSecret generates a wrong file!

**To Reproduce**
```
# create a secret from the java cacerts
kubectl create secret generic cacerts --namespace local-vault --from-file $JAVA_HOME/lib/security/cacerts

# reference it with an ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-cacerts
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-vault-store # <- Kubernetes Provider
  target:
    name: test-cacerts
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - remoteRef:
      key: cacerts
      property: cacerts
    secretKey: cacerts
```

**Expected behavior**
The generated secret is the same as the original secret, but:

**Original Secret**
cacerts:  171985 bytes

**Generated Secret with version 0.8.1**
cacerts:  171985 bytes

**Generated Secret >= 0.8.2**
cacerts:  264987 bytes

**Additional context**
Kubernetes 1.27.4 with k0s

**Comment by moolen** [comment] 2023-09-04 19:49
I can not reproduce the issue with the provided information. I tried to compare 0.8.1 to 0.8.2, both create a secret with the same data. Can you reproduce the issue from a clean install?

**Comment by moolen** [comment] 2023-09-05 12:08
Thanks for the manifests, bug confirmed!
This was introduced in https://github.com/external-secrets/external-secrets/pull/2106, will work on a fix soon. The root cause is a bug in the way ESO serialises the secret map.

**Comment by BenjaminNeale-Heritage** [comment] 2023-09-12 01:35
This sounds like a duplicate of https://github.com/external-secrets/external-secrets/issues/2375

**Closed** 2023-09-15 17:34 UTC
Labels: kind/bug
