### ISSUE TITLE
AWS SSM/ParameterStore KMS encryption

### ISSUE THREAD

**Issue by faust64** [external-secrets/external-secrets#2427] opened 2023-06-18 13:52 UTC
**Is your feature request related to a problem? Please describe.**
We're trying out that external secret operator, using AWS. Our context involves using AWS Parameter Store, and encrypting secrets, using KMS keys, based criticity, which platform that can then access those secrets, ...

While I could confirm ExternalSecrets are properly decrypting secrets, given proper privileges configured in AWS.
I'm unable to find some examples showing how I would push a secret, encrypting its value with arbitrary KMS keys.
Starting to suspect this was not yet implemented?

**Describe the solution you'd like**
Being able to define, either at PushSecret or SecretStore level, the KMS key that should be used encrypting secret when pushing its value to AWS.
Ideally: should support KMS key aliases, as an input.

**Describe alternatives you've considered**
Writing it myself ... we already have ansible roles managing those secrets from our own workstations. We're also investigating ansible-operator / operator-sdk, which is pretty nice repackaging our existing automation into operators ... While I'm PoC-ing a new CI/CD stack for my company, I'm just about to give up on that external-secrets-operator and code one myself, only handling our specific use case ...

Still, it's been nice playing with this operator, it's already a pretty good start.

**Additional context**
N/A

**Comment by moolen** [comment] 2023-06-21 19:20
Hey @faust64, thanks for this feature request. For context: we've envisioned the KMS encryption config to be defined on the SecretStore level: https://github.com/external-secrets/external-secrets/blob/main/design/002-pushsecret.md?plain=1#L57-L62. This hasn't been implemented yet, this is just a first design sketch. I'd be happy to discuss other approaches to configure encryption config for AWS/KMS.

**Comment by moolen** [comment] 2023-06-25 08:36
This is a duplicate of #2047, closing it.

**Closed by moolen** 2023-06-25 08:36 UTC
Labels: kind/feature, area/aws
