### ISSUE TITLE
Container exits on etcd timeout

### ISSUE THREAD

**Issue by moleskin-smile** [external-secrets/external-secrets#1725] opened 2022-11-17 02:41 UTC
On bigger Kubernetes clusters, when keyspace compaction happens, etcd sometimes responds slowly. It causes external secrets operator to exit, causing deployment failures.

Kubernetes version: 1.22
Kubernetes flavor: EKS
ES version: 0.6.1
External Secrets leader election is enabled.

Logs:

```
error retrieving resource lock external-secrets/external-secrets-controller: Get "https://10.100.0.1:443/apis/coordination.k8s.io/v1/namespaces/external-secrets/leases/external-secrets-controller": context deadline exceeded

failed to renew lease external-secrets/external-secrets-controller: timed out waiting for the condition

problem running manager

Stopping and waiting for non leader election runnables
```

These restarts are clearly correlated with etcd issues:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/20775179/202340420-16b68d82-abb1-4c91-8f0c-a4550e4d4e8b.png">

Thanks!

**Comment by moolen** [comment] 2022-11-18 19:36
I don't see the problem yet, ~20s seems like a normal timeframe for a container to take over leadership. AFAIK other controllers have similar behaviour. Is 20s not acceptable? 

In regards to throttling: this is also expected behaviour to protect api-server/etcd from getting bombarded with requests. Maybe tweaking [API Priority and Fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) can help resolve issues if you manage the control-plane yourself.

We use the [controller-runtime defaults](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.13.1/pkg/manager):

options related to leader election:
```go
type Options struct{
        // [...]
        // LeaseDuration is the duration that non-leader candidates will
	// wait to force acquire leadership. This is measured against time of
	// last observed ack. Default is 15 seconds.
	LeaseDuration *time.Duration

        // RenewDeadline is the duration that the acting controlplane will retry
	// refreshing leadership before giving up. Default is 10 seconds.
	RenewDeadline *time.Duration

	// RetryPeriod is the duration the LeaderElector clients should wait
	// between tries of actions. Default is 2 seconds.
	RetryPeriod *time.Duration
}
```

In regards to client-side ratelimiting external-secrets uses the controller-runtime defaults, too. They are [described here in-depth](https://danielmangum.com/posts/controller-runtime-client-go-rate-limiting/).

I agree, makes sense to make it configurable. Happy to review a PR if someone wants to take it :)

**Comment by moleskin-smile** [comment] 2022-11-24 17:44
> Is 20s not acceptable?

20 seconds without secret updates would be acceptable, sure. The problem is that restart or leader election means 20 minutes of lags in secret creation due to client-side throttling. It can be observed via the "workqueue depth" proxy metric:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/20775179/203841223-1f9390f2-099b-4c40-90c5-320261abe3c5.png">

This is in fact another problem – I wanted to tackle these unnecessary restarts first to make it less problematic (we use `0` as refresh interval on this bigger cluster). Experimenting with cache and throttling options would be next.

**Comment by moolen** [comment] 2022-11-24 20:55
Do you by any chance see which API calls get throttled? When the controller restarts it shouldn't do a lot of API calls and should be able to reconcile the ExternalSecrets swiftly. There may be an issue because it looks like we patch the status of an ExternalSecret with every reconciliation :thinking: 

Apart from that we can work towards sharding the controller workqueue.

**Comment by moolen** [comment] 2022-11-24 22:35
If we move the `patch` a bit further down we can improve the reconciliation speed:  

```diff
diff --git a/pkg/controllers/externalsecret/externalsecret_controller.go b/pkg/controllers/externalsecret/externalsecret_controller.go
index bf396341..57989eba 100644
--- a/pkg/controllers/externalsecret/externalsecret_controller.go
+++ b/pkg/controllers/externalsecret/externalsecret_controller.go
@@ -130,15 +130,6 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
                return ctrl.Result{}, nil
        }
 
-       // patch status when done processing
-       p := client.MergeFrom(externalSecret.DeepCopy())
-       defer func() {
-               err = r.Status().Patch(ctx, &externalSecret, p)
-               if err != nil {
-                       log.Error(err, errPatchStatus)
-               }
-       }()
-
        refreshInt := r.RequeueInterval
        if externalSecret.Spec.RefreshInterval != nil {
                refreshInt = externalSecret.Spec.RefreshInterval.Duration
@@ -176,6 +167,15 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
                }, nil
        }
 
+       // patch status when done processing
+       p := client.MergeFrom(externalSecret.DeepCopy())
+       defer func() {
+               err = r.Status().Patch(ctx, &externalSecret, p)
+               if err != nil {
+                       log.Error(err, errPatchStatus)
+               }
+       }()
+
        secret := &v1.Secret{
                ObjectMeta: metav1.ObjectMeta{
                        Name:      secretName,
```

test setup: one secret store, 1000 ExternalSecret resources.

1: code from main, `--concurrent=10`: takes ~5min to reconcile
2: code from main, `--concurrent=10, --enable-secrets-caching=true`: takes ~4min to reconcile
3: applied patch from above, including :point_up_2: args. I ran this a couple of times to verify the numbers

![eso-perf](https://user-images.githubusercontent.com/1709030/203869987-a835e3ba-9c0a-4378-b756-97008462f011.png)

Note: enabling secret cache will **increase memory usage** by a substantial amount but will reduce the load on the api-server (also throttling will happen less often)

**Comment by moleskin-smile** [comment] 2022-11-25 02:55
> Do you by any chance see which API calls get throttled?

Most throttling logs mention GETs:

```
Waited for *s due to client-side throttling, not priority and fairness, request: GET:https://10.100.0.1:443/api/v1/namespaces/*/secrets/*
```

But I can also see some logs about PATCH, PUT and POST requests. Throttling these is probably something we'd like to avoid... 🤔 

```
Waited for *s due to client-side throttling, not priority and fairness, request: PATCH:https://10.100.0.1:443/apis/external-secrets.io/v1beta1/namespaces/*/externalsecrets/*/status

Waited for *s due to client-side throttling, not priority and fairness, request: PUT:https://10.100.0.1:443/api/v1/namespaces/*/secrets/*

Waited for *s due to client-side throttling, not priority and fairness, request: POST:https://10.100.0.1:443/api/v1/namespaces/*/secrets
```

> Note: enabling secret cache will increase memory usage by a substantial amount but will reduce the load on the api-server (also throttling will happen less often)

Thanks. I don't know how to estimate this, so I'll increase limit to 2G and tune it later (we have ~4600 ES resources).

Anyway your results look amazing. Thanks for working on this.

**Comment by moolen** [comment] 2022-11-30 20:31
> I don't know how to estimate this

The controller (as of today) only stores the [secret metadata](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L502) in memory. I.e. it depends on the amount of labels/annotations you have on the secrets. It's likely less than 1kb per secret.

We have quite a lot of GET requests - this is because we lookup the existing secret and see if it needs an update. Want to avoid calling upstream APIs which are most of the time billed by API request.

There's probably room for improvement if we allow caching of the whole secret resource (i.e. no GET requests needed, everything is pulled from cache). But this may increase memory usage by a lot (we've had that in the past, that may be up to 1MB per secret)

**Comment by moleskin-smile** [comment] 2022-12-01 00:05
We ended up allocating 3 GiB for controller containers in our biggest cluster, so caching whole resources would probably be risky...

**Comment by moolen** [comment] 2022-12-14 16:44
@moleskin-smile is there anything left to do from your perspective? above :point_up_2: fix has been released recently, did you have the time to take a look at it if it improves your controller restart situation?

**Comment by moleskin-smile** [comment] 2022-12-23 02:11
Hey, sorry I must have missed your comment. We'll upgrade next week and I'll let you know about the results.

**Comment by moleskin-smile** [comment] 2023-02-11 18:12
@moolen: sorry for the delay. We upgraded and have been looking at performance for a while and I must say that this change (together with configuration changes mentioned above) made the performance problem disappear completely. Big thanks again!

**Comment by moolen** [comment] 2023-02-12 08:44
Hey, thanks for coming back, i'm glad to hear it helped! Also thanks for reporting this issue :bow:! 
Gonna close this as it is resolved, feel free to comment/reopen if this issue reappears.

**Closed** 2023-02-12 08:45 UTC
