### ISSUE TITLE
Unable to create external secrets after different interval of times

### ISSUE THREAD

**Issue by sbmtn** [external-secrets/external-secrets#2885] opened 2023-11-17 08:08 UTC
**Describe the bug**
Once, all three deployments for External Secrets Operator are successfully running in external-secrets namespace. The ClusterSecretStore is also successfully configured and the external secrets are also being successfully created and synced. But after sometime the Webhook deployment experiences some restarts and now, there's this error when trying to create more external secrets:

```
Error from server (InternalError): error when creating "test-preprod.yaml": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: Post "https://external-secrets-operator-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "external-secrets")
```

The webhook pod give following error:
```
2023/11/17 08:06:25 http: TLS handshake error from xx.xxx.xx.x:xxxxx: remote error: tls: bad certificate
```

There's no certManager configured for ESO deployment, relying on ESO to create and manage with a certificate on its own. But it seems like that has some issues.

**To Reproduce**
1. wait for sometime and once there're some restarts in webhook deployment, the error occurs when trying to create anymore external secrets

**Comment by gusfcarvalho** [comment] 2023-11-17 10:03
Unfortunately, these steps are not reproducible! If you do:
```
minikube start
helm install external-secrets external-secrets/external-secrets
```
You'll see the webhook never crashes.

So, this is something specific to your environment.

Can you share more information about your deployment? e.g. what are the values.yaml you're using to configure the operator? Where is it deployed, on which kubernetes version? Which operator version are you using?

**Comment by sbmtn** [comment] 2023-11-17 10:56
Hello @gusfcarvalho, here's more information that i can provide:

**Versions**
Kubernetes Version: `1.24.14`
External Secrets Operator Helm Chart Version: `0.9.3`

**Installatiion**
External Secrets Operator is deployed via Helm and for the custom-values provided during installation, are just for namespace, resources, service account.

**Issue Briefs**

- There's no certManager on the cluster, so `webhook.certManager.enabled` is default (i.e. false), assuming ESO will create and use its own certificate with the `webhook` and `validatingwebhookconfigurations`.
- After deployment, status of all pods can be seen successfully running. And after creating ClusterSecretStore, the external secrets created can be seen successfully syncing from Hashicorp Vault.
- From the cert-controller, webhook pod logs and webhook secret, a certificate can be obtained with expiry > 10 years. Webhook pod logs indicate that certificate is valid and everything is fine:
```
{"level":"info","ts":1700214970.451546,"logger":"setup","msg":"validating certs"}
{"level":"info","ts":1700214970.4520447,"logger":"setup","msg":"certs are valid"}
```
- Still, after some time, webhook pod is seen to be restarted mutliple times and the webhook pod logs now have following:
```
http: TLS handshake error from 10.100.30.0:46142: EOF
http: TLS handshake error from 10.100.30.0:46172: EOF
http: TLS handshake error from 10.100.30.0:46172: remote error: tls: bad certificate
http: TLS handshake error from 10.100.30.0:46172: remote error: tls: bad certificate
```
- Now, when creating the external secrets, there's this error:
```
Error from server (InternalError): error when creating "test-preprod.yaml": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: Post "https://external-secrets-operator-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "external-secrets")
```

**Comment by sbmtn** [comment] 2023-11-22 06:48
@gusfcarvalho any update or any point of contact regarding this? I still feel this issue is more of a `kind/bug` than just a `kind/needs-information` until we have anymore insights.

**Comment by gusfcarvalho** [comment] 2023-11-22 08:49
we put `kind/needs-information` whenever we cannot reproduce the issue, which is the case here.

Can you double check if the TLS contents from the CA certificate changed from this message:
```
{"level":"info","ts":1700214970.451546,"logger":"setup","msg":"validating certs"}
{"level":"info","ts":1700214970.4520447,"logger":"setup","msg":"certs are valid"}
```

to this message?
```
http: TLS handshake error from 10.100.30.0:46142: EOF
http: TLS handshake error from 10.100.30.0:46172: EOF
http: TLS handshake error from 10.100.30.0:46172: remote error: tls: bad certificate
http: TLS handshake error from 10.100.30.0:46172: remote error: tls: bad certificate
```

**Comment by gusfcarvalho** [comment] 2023-11-22 08:50
please also double check if the `CA Certificate` configuration of the `ValidatingWebhookConfiguration` is still the same regarding the one in the `external-secrets-webhook` Secret.

**Comment by sbmtn** [comment] 2023-11-22 09:55
Hey @gusfcarvalho, the age of the kubernetes secret is same since we deployed ESO on our cluster but the certificate content seems to have changed since then. But the new certificate is same on both resources - `external-secrets-webhook` kubernetes secret and `ValidatingWebhookConfiguration`

**Comment by sonyafenge** [comment] 2023-11-22 17:05
I have same issue when I use fluxcd and kind cluster to deploy following this instruction: https://external-secrets.io/v0.6.0/examples/gitops-using-fluxcd/
```
external-secrets   external-secrets-crs    91s   False   ExternalSecret/external-secrets/external-secret-approle-gitlab dry-run failed, reason: InternalError: Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": dial tcp 10.96.38.99:443: connect: connection refused...
```

**Comment by Skarlso** [comment] 2023-11-22 17:09
It looks like a timing error. It tried to apply something before the webhook was fully operations.

**Comment by sbmtn** [comment] 2023-11-28 06:06
@Skarlso I am not sure how this can be the timing issue here. I will give you a brief on the issue we're facing.

We have got ESO deployed in our cluster, all three pods/deployments are running fine, no cert issue, nothing. After sometime, let it be days or hours, the webhook and cert-controller pods show restarts. And soon, we get the `remote error: tls: bad certificate` in webhook pod logs and now when creating the exernal secrets, they fail and we get following response:

```
Error from server (InternalError): error when creating "test-preprod.yaml": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": failed to call webhook: Post "https://external-secrets-operator-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "external-secrets")
```

Manually restarting webhook pod and cert-controller pod if that's failing, do fix this. But we cannot rely on this since, its intermittent. We doubted if there's a certificate mismatch between our k8s secret for operator the validating webhook configuration so we monitored them. During the interval when everyhting was working fine with ESO and the external secrets the certificate content in the k8s secret and the validating webhook configuration did was different from before but the new content was same for both of them, due to which i guess ESO still worked. But we still dont know why the cert content was different from before even though the age of the certificate was same.

We were waiting for this to reproduce and it started happening yesterday on one of our cluster, until last week everything was fine.

**Comment by moolen** [comment] 2023-11-28 06:50
Please check the audit logs to see who modified the webhook tls Secret.

Because we see an `unknown authority` error please also try to establish a tls handshake and verify the certificate that is presented to you (do DNS names match, who is the issuer?).

Please also verify the caBundle on the ExternalSecret and SecretStore CRDs, they should have the same CA.

**Comment by sbmtn** [comment] 2023-11-30 06:30
@moolen Can there be any cert rotation config that maybe affecting us here? Will tuning `--check-interval` and `--crd-requeue-interval` help our case?

About the unknown authority for the cert issue from logs, we are not managing any cert for our eso deployment. ESO cert-controller must take care of that part and the tls handshake.

**Comment by sbmtn** [comment] 2023-11-30 08:13
@moolen can we connect sometime as per you availability, so that I can show you what's happening? I tried to explain the situation we're facing and the details on every component involved but we're not able to get any response that helps us in any way.

**Comment by sbmtn** [comment] 2023-12-04 06:49
@moolen any update?

**Comment by sbmtn** [comment] 2023-12-05 06:55
Hey @moolen, I did try to include every detail in above thread and it contains the answer to all you've asked. Here's everything you asked for:

**How do you install ESO?** 
Using helm chart.

**How many ESO deployments per cluster do you have?** 
I am not sure what does that mean, but we have one ESO installed in external-secrets namespace, which contains 3 deployments (i.e. operator, cert-controller and webhook). And we have one KES deployment in default namespace, which we were using previously and now planned to migrate to ESO.

**Do you run any GitOps tools like flux or ArgoCD?** 
Yes, the microservice applications gets deployed to our clusters via ArgoCD. External Secrets manifests are stored with argocd application code.

**If you use the official helm chart, can you share the helm values that you install ESO with?**
We just gave the custom resource values for operator pod, and verified that resources were under-utilised, so they couldn't be the issue.

**Can you reproduce the issue on your end? How much time do you have to wait until the issue re-occurs?**
No, we cannot its intermittent.

I am not sure how these details will help us here, since we had a working environment where everything was working as expected but we have this issue intermittently making our external secrets deployment fail and at the moment we just restart the ESO deployments as hotfix for this. Do you understand the issue that we're experiencing?

**Comment by jasongaunt** [comment] 2024-01-26 15:46
Just adding a comment here that will hopefully help people stumbling on this from Google (like I did). Adding an `ExternalSecret` that used a `ClusterSecretStore` in K8s (1.24) would error out as reported by others above.

Bouncing the webhook pod seems to resolve the issue:

* Find the webhook pod with `kubectl get pods -n MYNAMESPACE | grep external-secrets-webhook` 
* Delete that pod with `kubectl delete pod -n MYNAMESPACE external-secrets-webhook-1234567890-abcde`
* Let it recycle automatically and notice everything works again

Ps. For the maintainers, here's answers to your questions:

* How do you install ESO? _Helm chart 0.9.9 - although I see there's a later release that may fix it_
* How many ESO deployments per cluster do you have? _Just the one as `ClusterSecretStore`_
* Do you run any GitOps tools like flux or ArgoCD? _Nope_
* Can you share the helm values that you install ESO with? _Sadly not as it's not owned by me, but the only thing that was changed from the defaults were under `serviceAccount` to match our environment_
* Can you reproduce the issue on your end? _How much time do you have to wait until the issue re-occurs? After a couple of redeploys after trying to get this working :D_

**Comment by sbmtn** [comment] 2024-01-29 08:34
Hello @gusfcarvalho @moolen @Skarlso, this issue has been resolved in my setup and I am thankful for all your support regarding the issues I raised. I am fine with closing this issue if you may.

**Comment by Skarlso** [comment] 2024-01-29 14:59
What was the problem?

**Comment by Frikitrok** [comment] 2024-02-14 11:30
@sbmtn hey, how did you solve it? i can see identical issue on EKS 1.25

**Comment by sbmtn** [comment] 2024-02-15 07:14
Hey @Skarlso @Frikitrok, for what was the issue I was facing, that's explained in this issue quite briefly. But the reason for that to be happening, it was actually or CI/CD job for deploy ESO in our cluster which was running very frequently and updating the certificate generated by cert-controller, resulting into cert discrepancy for the ESO secret and the ESO webhook to validate.

**Comment by Skarlso** [comment] 2024-02-15 07:42
Thanks for the extra info. Can we close this?

**Comment by sbmtn** [comment] 2024-02-15 08:11
Yes @Skarlso we can close this one as I already asked you since its resolved now

**Closed** 2024-02-15 08:19 UTC
Labels: triage/needs-information
