### ISSUE TITLE
modify AWS ParameterStore provider to use GetParametersByPath API instead of DescribeParameters

### ISSUE THREAD

**Issue by mmerickel** [external-secrets/external-secrets#1066] opened 2022-05-01 22:34 UTC
**Describe the solution you'd like**

When using a `dataFrom` template with a `find` operator, the provider currently uses `DescribeParameters` with a filter followed by a second `GetParameter` query for each key that matches the regex. The provider should be using the purpose-built `GetParametersByPath` with `Recursive=true` API.

**What is the added value?**

1. The provider currently uses at least one API call to list the parameters, plus one API call per matched parameter to get the value. This could be reduced to a single API call for the entire lookup.
2. The provider currently requires the IAM policy allow access to list all of the parameters in the account, instead of only the prefix passed in by the `path` parameter to the `find` operator. There is not a way to limit the `DescribeParameters` access to a path prefix.

**Give us examples of the outcome**

There should be no changes to the CRD or public API, only the IAM policies for users.

**Observations (Constraints, Context, etc):**

Tags are not currently supported in the parameter filter for `GetParametersByPath` but my use case does not require them. It would be possible to fallback to the current implementation if tags are required.

**Comment by mmerickel** [comment] 2022-12-10 16:39
not stale

**Comment by moolen** [comment] 2023-05-25 18:42
Fixed with #2350, duplicate of #1839

**Closed by moolen** 2023-05-25 18:42 UTC
Labels: kind/feature, area/aws
