### ISSUE TITLE
Webhook returns tls: bad certificate

### ISSUE THREAD

**Issue by Duologic** [external-secrets/external-secrets#997] opened 2022-04-14 08:30 UTC
The webhook has been returning this error spuriously on all our clusters:

```
2022/04/13 22:40:01 http: TLS handshake error from 172.24.0.182:49554: remote error: tls: bad certificate
```

On Flux logs we see:

```
"kubectl apply -f -","err":"running kubectl: exit status 1, stderr: Error from server (InternalError): error when applying patch:
{\"spec\":{\"dataFrom\":[{\"extract\":{\"key\":\"flux/fluxcloud\"}}]}}
to:
Resource: \"external-secrets.io/v1beta1, Resource=externalsecrets\", GroupVersionKind: \"external-secrets.io/v1beta1, Kind=ExternalSecret\"
Name: \"fluxcloud\", Namespace: \"flux\"
for: \"STDIN\": Internal error occurred: failed calling webhook \"validate.externalsecret.external-secrets.io\": Post \"https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s\": x509: certificate signed by unknown authority"
```

It feels related to something that Flux does.

ESO Version: 0.5.1

Things I've tried:
- restarted the pods/deployments
- curl the service directly (no error)

Things that work
- ExternalSecrets and SecretStores can be applied (flux/kubectl)
- ExternalSecrets are sync'd

Any suggestions on how we can further debug this?

**Comment by Duologic** [comment] 2022-04-14 08:54
I was able to reproduce with curl:

```
root@test:/# curl -v https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret
*   Trying 10.189.214.125:443...
* Connected to external-secrets-webhook.external-secrets.svc (10.189.214.125) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

With `openssl s_client`:
```
root@test:/# openssl s_client -connect external-secrets-webhook.external-secrets.svc:443
CONNECTED(00000003)
depth=0 CN = external-secrets-webhook.external-secrets.svc
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = external-secrets-webhook.external-secrets.svc
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = external-secrets-webhook.external-secrets.svc
verify return:1
---
Certificate chain
 0 s:CN = external-secrets-webhook.external-secrets.svc
   i:O = external-secrets, CN = external-secrets
---
Server certificate

-----BEGIN CERTIFICATE-----
<redacted>
-----END CERTIFICATE-----
subject=CN = external-secrets-webhook.external-secrets.svc

issuer=O = external-secrets, CN = external-secrets

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1435 bytes and written 401 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
    Session-ID: 0075775B4B425699CE5EAD94E6ECC0844CF26E1910B6B2B8733F72F013E07C9C
    Session-ID-ctx:
    Resumption PSK: F0715910E38A9BC72E70A2C8B0775AE458B6A75CD4F932B061B3A5000A3645A8
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket: <redacted>

    Start Time: 1649926325
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no
    Max Early Data: 0
```

**Comment by Duologic** [comment] 2022-04-14 09:20
The error happens when Flux is trying to patch/apply a few specific ExternalSecret objects.

**Comment by Duologic** [comment] 2022-04-14 09:23
> One thing that the certController pod does is actually configure both ValidatingWebhookConfiguration and CRDs with the certificate authority information, so the first check would be if Flux is somehow erasing this configuration after a while.

That could be it, we deploy our CRDs with Flux. Any suggestions to fix this?

**Comment by Duologic** [comment] 2022-04-14 09:26
When running kubectl apply/diff locally, I also see a constant drift on the CRDs, this does not work well in a GitOps context tbh.

**Comment by gusfcarvalho** [comment] 2022-04-14 10:38
I really don't see any way around this which doesn't involve either an post-install `ignore` on CRDs and `ValidatingWebhookConfiguration`. Even if we tried to use cert-manager we would have the same drift, as the `caInjector` will effectively change these two resource types.

I'm not that familiar with flux, but is there a way to ignore specific fields from the specification?

I'm asking this because this is going to be a recurrent issue, since certificates expire.

**Comment by gusfcarvalho** [comment] 2022-04-14 10:41
The drift you are seeing is the conversion webhook configuration that the certController is loading. This is due to the fact that, due to a Kubernetes design decision, this is where the Conversion Webhook configuration lives.

**Comment by gusfcarvalho** [comment] 2022-04-14 11:22
Related to your issue, can you verify if this ValidatingWebhookConfiguration is being changed as well? `external-secrets-validate`

The other possibility is that flux is changing the secret where the certificate is stored. You can find it with `kubectl get secrets -A -l external-secrets.io/component=webhook`

**Comment by Duologic** [comment] 2022-04-14 11:39
>I'm not that familiar with flux, but is there a way to ignore specific fields from a resource?


We rely on Flux v1, it does a simple `kubectl apply` with very little meddling in between. I'm not aware of being able to ignore certain fields, and if so I'd prefer something native to Kubernetes rather than part of Flux to prevent this issue from reoccuring in case we change the CD system. The constant drift does not feel right and I assume other CD systems have a high chance of also being affected by this. Note, also don't use Helm to deploy to our clusters, we generate plain manifests and then let CD do the sync.

I wonder why we haven't seen this problem before, how do other controllers/operators deal with this problem?


> Related to your issue, can you verify if this ValidatingWebhookConfiguration is being changed as well? external-secrets-validate

Yes

> The other possibility is that flux is changing the secret where the certificate is stored. You can find it with kubectl get secrets -A -l external-secrets.io/component=webhook

What do you mean by this? What would it change?

We don't deploy the Secrets through Flux, however this time it did (because of another issue). What struck me as odd is that the secret is empty when it gets rendered by Helm. Why generate a manifests when it has no contents? Perhaps this should all happen in-cluster rather than with Helm?

I'll be disabling the deployment of that Secret through Flux to be sure it doesn't intervene with the object.

**Comment by gusfcarvalho** [comment] 2022-04-14 13:12
> I wonder why we haven't seen this problem before, how do other controllers/operators deal with this problem?

This is the thing that I've been trying to look at. IIRC, when they have a ValidatingWebhookConfiguration, they tend to either use `cert-manager` (which uses the same steps we are using) or they generate certificates upon install time, where users can configure certificates to be available. Providing certificates to helm would work for the ValidatingWebhookConfiguration, but it would feel weird to overtemplate the CRD and have helm to mess there as well. 

I think I can provide some additional helm values to allow this possibility for the ValidatingWebhookConfiguration anyways.

> We don't deploy the Secrets through Flux, however this time it did (because of another issue). What struck me as odd is that the secret is empty when it gets rendered by Helm. Why generate a manifests when it has no contents? Perhaps this should all happen in-cluster rather than with Helm?

We need to have a secret defined in order to properly load the certificates (when they are available) to the webhook. If there is no secret, the webhook will be in a pending state.

> I'll be disabling the deployment of that Secret through Flux to be sure it doesn't intervene with the object.

The issues that I think are currently happening:
* The secret content is being deleted by flux, causing certificates to go missing
* ValidatingWebhookConfiguration CA configuration is getting deleted by flux, causing `apiserver` to not know which is the certificate authority.

Even if you create a Secret on your own (which would be fine for the cert Controller), My guess is that the ValidatingWebhookConfiguration will still get changed, so your issue will still be present.

**Comment by Duologic** [comment] 2022-04-14 15:18
> We need to have a secret defined in order to properly load the certificates (when they are available) to the webhook. If there is no secret, the webhook will be in a pending state.

Can't we have the cert-controller create that object in k8s before trying to update it?

I had a look at the CRDs for cert-manager on our end, which can deployed through the same mechanism. When running apply/diff, this doesn't show a diff even though the `spec.conversion.clientConfig.caBundle` also unset locally and configured in-cluster.

There is however another changed (besides the caBundle), the diff also shows that the `spec.conversion.clientConfig.service.name|namespace` also changes. 🤨

**Comment by gusfcarvalho** [comment] 2022-04-14 15:43
Is there any specific configuration you are setting for cert manager that makes it ignore the changes to the CRD?

**Comment by gusfcarvalho** [comment] 2022-04-14 17:36
> Can't we have the cert-controller create that object in k8s before trying to update it?

I believe yes, but it wouldn't matter for you. If you try to set this secret after you deploy it (just to test it) you will see you will still have your issue. The issue is coming from the fact that flux is trying to control CRDs and ValidatingWebhookConfiguration for ESO and not for cert-manager in your case.

I believe we can try to do some one of the following improvements:
1.a) Allow users to use existing secrets instead of only creating an empty secret.
1. b) Allow users to input a caBundle to go under the ValidatingWebhookConfiguration

2.a) Make `webhook` read from secrets (thus not needing the secret Mount)
2.b) Make `certController` create secrets instead of updating them (this is actually what cert-manager does, inside the webhook deployment).

However I still believe this would not cover your issue.

@knelasevero @moolen do you have any other insight / past experience with flux?

**Comment by Duologic** [comment] 2022-04-14 19:31
I agree, I came to the same conclusion too that the secret is not the problem, the diff/drift is. If we find out what is different between cert-manager and ESO, then I believe we can resolve this.

**Comment by Duologic** [comment] 2022-04-14 20:02
I found this issue which seems to describe our problem: https://github.com/kubernetes-sigs/kubebuilder/issues/1684

**Comment by Duologic** [comment] 2022-04-14 20:23
In a dev cluster I was able to try it out:

- removed the `caBundle` attribute from the CRD on the cluster (and turned off flux for the sake of testing)
- observed that `caBundle` was set again in the CRD on the cluster
- removed the `caBundle` attribute from the CRD manifest before apply
- ran kubectl apply
- no diff :tada:

**Comment by Duologic** [comment] 2022-04-14 20:28
I'd suggest having this change in the Helm chart on the CRDs:

```diff
       clientConfig:
-        caBundle: Cg==
         service:
-          name: kubernetes
-          namespace: default
+          name: {{ include "external-secrets.fullname" . }}-webhook
+          namespace: {{ .Release.Namespace | quote }}
           path: /convert
```

I had a brief look at the code that generates the Helm Chart, this isn't a straightforward change for what I could see.

**Comment by Duologic** [comment] 2022-04-14 21:38
We have a workaround for this on our end, I've created a PR that should fix it properly.

Thanks for your patience and working through this with me as this was an intercate problem.

**Comment by Duologic** [comment] 2022-04-15 15:14
I have deployed above changes to all our clusters and the certificate errors on Flux are gone.

**Closed** 2022-04-19 19:43 UTC
Labels: triage/support, area/webhook
