### ISSUE TITLE
Validate `.data[].secretKey` duplicates

### ISSUE THREAD

**Issue by Dgadavin** [external-secrets/external-secrets#2921] opened 2023-12-04 08:16 UTC
**Describe the bug**
I have same `secretKey` `SERVICE_NAME` but point to diferenet parameters in AWS Parameter Store. I see that operator take the last one in YAML and inject into the secret. So in my example into `test` secret I will go `SERVICE_NAME` from ` /dev/project_env_vars` Parameter instead of `/dev/shared_env_vars` Parameter. 

**To Reproduce**
I have such Externalsecret
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test
  namespace: default
spec:
  secretStoreRef:
    name: ssm-secret-store-global
    kind: ClusterSecretStore
  refreshInterval: "3m"
  target:
    name: test-env
    creationPolicy: 'Owner'
  data:
    - secretKey: SERVICE_NAME
      remoteRef:
        key: /dev/shared_env_vars
        property: TEST_URL
    - secretKey: KAFKA_BROKER_0
      remoteRef:
        key: /dev/shared_env_vars
        property: KAFKA_BROKER_0
    - secretKey: KAFKA_BROKER_1
      remoteRef:
        key: /dev/shared_env_vars
        property: KAFKA_BROKER_1
    - secretKey: KAFKA_BROKER_2
      remoteRef:
        key: /dev/shared_env_vars
        property: KAFKA_BROKER_2
    - secretKey: SERVICE_NAME
      remoteRef:
        key: /dev/project_env_vars
        property: SERVICE_NAME
```

**Expected behavior**
Error. I want to see some kind of duplication error. This is not transperent behaviour because you can inject wrong parameter.

Operator version: **0.9.3**

**Comment by moolen** [comment] 2023-12-04 18:31
Hey! Thanks for the suggestion :+1: 
I'd say it works as intended, but this should be caught by validation :smile:

**Comment by Dgadavin** [comment] 2023-12-04 18:35
Yeah. Maybe this is not actually the bug but with secrets much safer to have an error if someone will duplicate secret name. This can produce unexpected issue :)

**Comment by gusfcarvalho** [comment] 2023-12-04 20:20
One thing to note though: this behavior should not error on different deletion policies, as other users use this to create “default” configuration

**Comment by shuheiktgw** [comment] 2023-12-21 22:45
Closing the issue according to https://github.com/external-secrets/external-secrets/pull/2929#issuecomment-1867020690

**Closed** 2024-01-14 17:09 UTC
Labels: good first issue, kind/feature
