### ISSUE TITLE
BREAKING CHANGE - Unable to create k8s secrets with name larger than 55 characters with v0.9.3

### ISSUE THREAD

**Issue by vb250182** [external-secrets/external-secrets#2616] opened 2023-08-16 13:00 UTC
**Describe the bug**
In previous versions, we were able to create k8s secrets through ESO with a name larger than 55 characters. Now, when we create an external-secrets with 56-63 characters, the external-secrets resource gets created, but the k8s secret cannot.

**To Reproduce**
1. provide all relevant manifests

ESO YAML that fails to create the k8s secret with a name with 56 characters.
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unable-to-create-long-name-secrets-anymore-1234567890123
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: ESO_ISSUE_0_9_3
      version: latest
    secretKey: result
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: es-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
```

3. provide the Kubernetes and ESO version
kubernetes: 1.25.10-gke.1200
ESO: v0.9.3

**Expected behavior**
In previous versions, we were able to create secrets that were at least 61 characters long. 
We expect the same behavior as before.

**Screenshots**

Unable to create k8s secret:
<img width="763" alt="image" src="https://github.com/external-secrets/external-secrets/assets/33496975/8aee62d5-5daa-4917-85f9-08c0daa9008c">

Secret created successfully with 55 characters in the name field
<img width="717" alt="image" src="https://github.com/external-secrets/external-secrets/assets/33496975/5a5b3b66-3c3a-4045-ab28-93b35d8ea72e">

**Additional context**

**Comment by terrpan** [comment] 2023-08-17 09:52
I can confirm that we have the same issue on 0.9.3. The secret name is only 20 characters, but the namespace name is actually very long, 50 characters.

I did a rollback to 0.9.0 and that fixed my problems.

**Comment by mschultz-aofl** [comment] 2023-08-17 16:48
We're seeing the same issue as well. It's not deleting old secrets, but it's creating new secrets. I see that the `binding` status section is showing as `binding: {}` but otherwise everything is reporting as successful with no errors in the logs (e.g., secret sync'd status, last transition time updated, successful sync log messages in the ESO operator container, etc)

**Comment by mittalsuraj18** [comment] 2023-08-20 13:38
Same issue here. Rolling back to 0.9.2 seems to have fixed it.

**Comment by adelmoradian** [comment] 2023-08-21 12:16
0.9.2 also worked for me!

**Comment by caseyrobb** [comment] 2023-08-22 14:04
Downgrading to 0.9.2 worked for me as well.  In OCP 4.12, I left the operator at v0.9.3 and updated the OperatorConfig instance to use the previous image:

`YAML
spec:
  certController:
    image:
      repository: "ghcr.io/external-secrets/external-secrets"
      tag: "v0.9.2"
Collapse`

**Comment by marcingy** [comment] 2023-08-22 14:12
We are also getting issues in 0.9.3 where secrets are unreadable, it is in intermittent and does not affect all secrets > 55. Reverting to 0.9.2 fixes the issue

**Comment by MedhatNakhla** [comment] 2023-08-22 17:32
You can just revert back to 0.9.2

**Comment by moolen** [comment] 2023-08-22 21:16
Just looking at this now after coming back from vacation :palm_tree:. 

It apparently is broken and the moment (thanks for reporting it everyone!) and i'm leaning towards reverting both https://github.com/external-secrets/external-secrets/commit/9c9bd73e90e18654671a9f35a0b92c65d56a167e and https://github.com/external-secrets/external-secrets/commit/ad111cc180fd054ec7e9a10b8b9782508fbd699d and fix it up with an extra PR.

Due to character limitations we would have to split the resource name + namespace (each up to 253 characters) into segments and store them in different labels due to its length limitations (63 characters). This is ugly, but doable. I'd be glad if we can find a different approach (store it in an annotation + GC goroutine maybe?).

@gusfcarvalho did you start looking into the owner label issue? A release for 0.9.4 has been requested already, I'd like to include a fix for this issue as well (probably by just reverting it).

**Comment by mschultz-aofl** [comment] 2023-08-22 21:24
@moolen Another option might be storing a sha1 hash of the namespace+name instead of the full name - then, keep an internal map of hashes to the resource so that you don't have to keep doing sha1 hashes on each check. This would been roughly half a kb per resource at most (although probably on average, 150b). Could get memory heavy, so it may need to be stored on a temp file instead, but eliminates needing to manage a bunch of labels or annotations.

**Closed** 2023-08-23 16:16 UTC
Labels: kind/bug
